In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# Mean

In [3]:
df['fare'].mean()

np.float64(32.204207968574636)

In [4]:
df['age'].mean()

np.float64(29.69911764705882)

In [5]:
df['fare'].median()

14.4542

In [9]:
from scipy import stats
data = np.array([1, 2, 3, 4, 5])
stats.gmean(data)

np.float64(2.6051710846973517)

In [11]:
stats.hmean(data)

np.float64(2.18978102189781)

In [12]:
data.mean()

np.float64(3.0)

In [13]:
stats.tmean(data)

np.float64(3.0)

In [14]:
stats.trim_mean(data, 0.2)

np.float64(3.0)

# Median

In [15]:
df['age'].median()

28.0

In [16]:
df['fare'].median()

14.4542

# Mode

In [17]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [18]:
df['age'].mode()

0    24.0
Name: age, dtype: float64

In [19]:
df['embark_town'].mode()

0    Southampton
Name: embark_town, dtype: object

In [20]:
df['class'].mode()

0    Third
Name: class, dtype: category
Categories (3, object): ['First', 'Second', 'Third']

In [21]:
df['class'].unique()

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [22]:
df['class'].nunique()

3

In [23]:
df['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64